//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMDatabaseEntities : DbContext
    {
        public HMDatabaseEntities()
            : base("name=HMDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing> Billings { get; set; }
        public virtual DbSet<Elective> Electives { get; set; }
        public virtual DbSet<Emergency> Emergencies { get; set; }
        public virtual DbSet<GeneralWard> GeneralWards { get; set; }
        public virtual DbSet<ICU> ICUs { get; set; }
        public virtual DbSet<OrthopaedicWard> OrthopaedicWards { get; set; }
        public virtual DbSet<PaediatricWard> PaediatricWards { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<SurgicalWard> SurgicalWards { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
