//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Billings = new HashSet<Billing>();
            this.Electives = new HashSet<Elective>();
            this.Emergencies = new HashSet<Emergency>();
            this.GeneralWards = new HashSet<GeneralWard>();
            this.ICUs = new HashSet<ICU>();
            this.OrthopaedicWards = new HashSet<OrthopaedicWard>();
            this.PaediatricWards = new HashSet<PaediatricWard>();
            this.SurgicalWards = new HashSet<SurgicalWard>();
        }
    
        public string PatientID { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Category { get; set; }
        public string Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string MaritalStatus { get; set; }
        public string Occupation { get; set; }
        public string Religion { get; set; }
        public string GP { get; set; }
        public string Insurance { get; set; }
        public string AdmissionType { get; set; }
        public string Consultant { get; set; }
        public string Ward { get; set; }
        public string BedNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elective> Electives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergency> Emergencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralWard> GeneralWards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICU> ICUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrthopaedicWard> OrthopaedicWards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaediatricWard> PaediatricWards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurgicalWard> SurgicalWards { get; set; }
    }
}
